### ISSUE TITLE
无掉落截图被识别成“此张图片未通过质量监测”

### ISSUE THREAD

**Issue by Tinhone** [penguin-statistics/recognizer#10]
![图片](https://user-images.githubusercontent.com/81268244/172471915-34e132a3-1c80-4e60-bcd2-ef6af9a412e5.png)
![图片](https://user-images.githubusercontent.com/81268244/172472069-df2d6cbe-bd8b-402f-9e60-02538f29acbb.png)
![图片](https://user-images.githubusercontent.com/81268244/172516967-ab3d10ac-0863-4980-9bed-30e24c3cac90.png)
如图

不太清楚这个bug应该往哪里报告...本来想往截图识别那里报告，但发现曾经报告的一个未掉落数据并不能被查询到，于是就来这里了

**Comment by AlvISsReimu** [comment]
这个出现的原因是SV-4预设掉落范围是必有非代币的常规掉落的，没想到竟然可以不掉落任何素材...已修复，感谢反馈！
