### ISSUE TITLE
国服9-19结算截图无法识别

### ISSUE THREAD

**Issue by qzlzdy** [penguin-statistics/recognizer#11]
显示无法识别
![image](https://user-images.githubusercontent.com/46930250/175796701-b1a90959-f0ee-431f-92f1-106c20968da9.png)
原截图
![Screenshot_20220621-093842](https://user-images.githubusercontent.com/46930250/175796709-9c929c83-e10b-4a40-9363-88e1c002abf8.png)
截了十多张都是同样的错误

**Comment by GalvinGao** [comment]
cc @KumoSiunaus

**Comment by KumoSiunaus** [comment]
Fixed
