### ISSUE TITLE
国服绿野幻梦活动结算截图识别失败

### ISSUE THREAD

**Issue by Bingqiling-W** [penguin-statistics/recognizer#12]
![捕获2](https://user-images.githubusercontent.com/63763165/177622525-82b39643-d4dc-475b-8528-aa9847d66506.PNG)
原截图
![image](https://user-images.githubusercontent.com/63763165/177622628-f1fe4356-6fc1-4178-941b-2d1906b81490.png)

![捕获](https://user-images.githubusercontent.com/63763165/177622867-c81478d7-4a47-49f4-ae6e-4ba1bf65ab68.PNG)
原截图
![image](https://user-images.githubusercontent.com/63763165/177622912-86ec37fd-795e-4b29-bb6c-1795ced4b1fc.png)

![捕获3](https://user-images.githubusercontent.com/63763165/177623077-93ce7515-2893-4a14-99c7-9c0861fec141.PNG)
原截图
![image](https://user-images.githubusercontent.com/63763165/177623105-193efdf7-9f9a-4df5-b570-734bcef8ee18.png)

**Comment by GalvinGao** [comment]
你好，我们已经修复对应问题，请尝试刷新页面后看下是否已经解决了呢

**Comment by Bingqiling-W** [comment]
这是最新的结果，但似乎还没有解决
![捕获](https://user-images.githubusercontent.com/63763165/177810384-a59b618f-93eb-4011-b92c-22b1872b2ef6.PNG)

**Comment by Bingqiling-W** [comment]
目前问题已解决，谢谢。
